In [2]:
import torch
x = torch.rand(5, 3)
print(x)

tensor([[0.0926, 0.3055, 0.2719],
        [0.9708, 0.6642, 0.1079],
        [0.9308, 0.9281, 0.8523],
        [0.9767, 0.6794, 0.5506],
        [0.4903, 0.0632, 0.3195]])


In [ ]:
import torch
import torchvision
import torchvision.transforms as transforms

In [3]:
import torch
flag = torch.cuda.is_available()
if flag:
    print("CUDA可使用")
else:
    print("CUDA不可用")

ngpu= 1
# Decide which device we want to run on
device = torch.device("cuda:0" if (torch.cuda.is_available() and ngpu > 0) else "cpu")
print("驱动为：",device)
try:
    print("GPU型号： ",torch.cuda.get_device_name(0))
finally:
    print('done')

CUDA不可用
驱动为： cpu
done


AssertionError: Torch not compiled with CUDA enabled

In [4]:
x = torch.Tensor(5, 3)
print(x)

tensor([[5.0381e-20, 1.4013e-45, 2.4807e-35],
        [1.4013e-45, 6.6406e-36, 1.4013e-45],
        [0.0000e+00, 0.0000e+00, 5.0231e-20],
        [1.4013e-45, 5.0231e-20, 1.4013e-45],
        [5.0231e-20, 1.4013e-45, 7.3810e-30]])


In [7]:
print(x.size())
y = torch.rand(5, 3)
print(x - y)

torch.Size([5, 3])
tensor([[-0.1789, -0.3607, -0.5929],
        [-0.6602, -0.4868, -0.3349],
        [-0.3704, -0.9332, -0.4308],
        [-0.5004, -0.6994, -0.5035],
        [-0.8579, -0.1669, -0.0665]])
